name: Orange Cactus Coffee
favicon: null
layout_spectrum: 0.8983620847575366
typography_spectrum: 0.4755411746446043
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f25a29'
    - '#525252'
    - '#f0f0f0'
    - '#b9b9b9'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
